Added name to contributors.json
TelWare-Hacktoberfest-2021/tw-hacktoberfest-21 pull request #15
Opened 2021-10-01 20:36 UTC by SMinervaTelware

Hacktotoberfest - added fake user

2021-10-04 15:27 UTC, mfisher-tw requested changes

2021-10-04 15:27 UTC, mfisher-tw commented on static/data/contributors.json
> +    {"name": "Test User", "ext": "3145", "url": "https://media-exp1.licdn.com/dms/image/C4E0BAQHR3nDWRbZROw/company-logo_200_200/0/1614707005483?e=2159024400&v=beta&t=Do7S2L8h93-T6lH_XvRiYdUrYYgugpVQ
@SMinervaTelware, I would say don't add the test user.  I can delete the entry I made for you so you can do it and get your PR if you want.

2021-10-04 17:33 UTC, SMinervaTelware commented
lol, no that's ok. I was just following along.

I will have other opportunities to get a tshirt 🙂




<https://www.telware.com/> [Logo] <https://www.telware.com/>

  Sara Minerva

   UX/UI Designer


  704.409.3509

  ***@***.***

  1824 Industrial Center Cir, Charlotte NC 28213


  Follow us  [Facebook icon] <https://www.facebook.com/TelWare>  [LinkedIn icon] <https://www.linkedin.com/company/telware-corporation>  [Twitter icon] <https://twitter.com/TelwareCorp>   | telware.com<http://telware.com/>



________________________________
From: mfisher-tw ***@***.***>
Sent: Monday, October 4, 2021 11:27 AM
To: TelWare-Hacktoberfest-2021/tw-hacktoberfest-21 ***@***.***>
Cc: Sara Minerva ***@***.***>; Mention ***@***.***>
Subject: Re: [TelWare-Hacktoberfest-2021/tw-hacktoberfest-21] Added name to contributors.json (#15)


**Caution: This email is from outside of the organization. Please think before you click**

@mfisher-tw requested changes on this pull request.

________________________________

In static/data/contributors.json<https://github.com/TelWare-Hacktoberfest-2021/tw-hacktoberfest-21/pull/15#discussion_r721475730>:

> @@ -3,5 +3,6 @@
     {"name": "Michael Fisher", "ext": "3144", "url": "https://s.gravatar.com/avatar/a5702d4f23a3869de0402ddb53a788c6?s=800"},
     {"name": "Sara Minerva", "ext": "3509", "url": "https://s.gravatar.com/avatar/1a17b8243224a52f34bc73fd654f129e?s=800"},
     {"name": "Sumner Robinson", "ext": "3138", "url": "https://s.gravatar.com/avatar/3380deb20db45e697c40c2444c3b615b?s=800"},
-    {"name": "Brian Longwell", "ext": "3145", "url": "https://media-exp1.licdn.com/dms/image/C4E0BAQHR3nDWRbZROw/company-logo_200_200/0/1614707005483?e=2159024400&v=beta&t=Do7S2L8h93-T6lH_XvRiYdUrYYgugpVQtWAvH9fLFAs"}
+    {"name": "Brian Longwell", "ext": "3145", "url": "https://media-exp1.licdn.com/dms/image/C4E0BAQHR3nDWRbZROw/company-logo_200_200/0/1614707005483?e=2159024400&v=beta&t=Do7S2L8h93-T6lH_XvRiYdUrYYgugpVQtWAvH9fLFAs"},
+    {"name": "Test User", "ext": "3145", "url": "https://media-exp1.licdn.com/dms/image/C4E0BAQHR3nDWRbZROw/company-logo_200_200/0/1614707005483?e=2159024400&v=beta&t=Do7S2L8h93-T6lH_XvRiYdUrYYgugpVQtWAvH9fLFAs"}


@SMinervaTelware<https://github.com/SMinervaTelware>, I would say don't add the test user. I can delete the entry I made for you so you can do it and get your PR if you want.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/TelWare-Hacktoberfest-2021/tw-hacktoberfest-21/pull/15#pullrequestreview-770450189>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ALZ5HXGQJUAM55SRKX5R52LUFHBXPANCNFSM5FFOTIGQ>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.

This e-mail and any documents accompanying this transmission is intended for the sole use of the individual or entity to who it is addressed. If you, the reader are not the intended recipient, you are hereby notified that any use, distribution, discussion, disclosure or copying of the message including any attachment(s) is strictly prohibited and may subject you to criminal or civil penalties. If you received this transmission in error, please contact the sender immediately and arrange for the return or destruction of these documents. Unauthorized interception of this e-mail communication is a violation of federal and applicable state law.

2021-10-05 12:08 UTC, mfisher-tw commented
Gotcha, I am just going to close this PR then.

2021-10-05 12:08 UTC, closed without merging